export type Konto = {
  kontonummer: string;
  kontobeskrivning: string;
  kontoklass: string;
  sökord: string[];
  kategori: string;
};

export const accounts = [
  {
    kontonummer: "4010",
    kontobeskrivning: "Inköp varor & material",
    kontoklass: "Kostnader",
    sökord: ["varor", "inköp", "material", "lager"],
    kategori: "Inköp varor & material",
  },
  {
    kontonummer: "5460",
    kontobeskrivning: "Inköp förbrukningsmaterial",
    kontoklass: "Kostnader",
    sökord: ["papper", "plastpåsar", "batterier"],
    kategori: "Inköp varor & material",
  },
  {
    kontonummer: "5410",
    kontobeskrivning: "Inköp förbrukningsinventarier",
    kontoklass: "Kostnader",
    sökord: ["dator", "telefon", "skrivare"],
    kategori: "Inköp varor & material",
  },
  {
    kontonummer: "6990",
    kontobeskrivning: "Böcker & E-publikationer",
    kontoklass: "Kostnader",
    sökord: ["böcker", "e-böcker", "tidningar"],
    kategori: "Inköp varor & material",
  },
  {
    kontonummer: "6230",
    kontobeskrivning: "IT-produkter / domännamn",
    kontoklass: "Kostnader",
    sökord: ["domän", "webbhotell", "server"],
    kategori: "Inköp varor & material",
  },
  {
    kontonummer: "5615",
    kontobeskrivning: "Leasing av bil",
    kontoklass: "Kostnader",
    sökord: ["leasing", "bil", "operationell leasing", "leasingavgift"],
    kategori: "Bil och transport",
  },
  {
    kontonummer: "5612",
    kontobeskrivning: "Bilförsäkring / bilskatt",
    kontoklass: "Kostnader",
    sökord: ["försäkring", "bilskatt", "fordonsskatt"],
    kategori: "Bil och transport",
  },
  {
    kontonummer: "5610",
    kontobeskrivning: "Drivmedel – inrikes / utrikes",
    kontoklass: "Kostnader",
    sökord: ["bensin", "diesel", "etanol", "bränsle"],
    kategori: "Bil och transport",
  },
  {
    kontonummer: "5618",
    kontobeskrivning: "Parkering",
    kontoklass: "Kostnader",
    sökord: ["parkering", "avgift", "garage"],
    kategori: "Bil och transport",
  },
  {
    kontonummer: "5619",
    kontobeskrivning: "Biltvätt",
    kontoklass: "Kostnader",
    sökord: ["biltvätt", "rengöring", "tvätta bil"],
    kategori: "Bil och transport",
  },
  {
    kontonummer: "7331",
    kontobeskrivning: "Milersättning",
    kontoklass: "Kostnader",
    sökord: ["aaaaaaaaaaaaaaaaaaaaaaaaaa"],
    kategori: "Bil och transport",
  },
  {
    kontonummer: "5616",
    kontobeskrivning: "Trängselskatt",
    kontoklass: "Kostnader",
    sökord: ["trängselskatt", "vägtull"],
    kategori: "Bil och transport",
  },
  {
    kontonummer: "5630",
    kontobeskrivning: "Transportmedelskostnader",
    kontoklass: "Kostnader",
    sökord: ["registreringsbevis", "fordonsavgifter", "trafikregister"],
    kategori: "Bil och transport",
  },
  {
    kontonummer: "5010",
    kontobeskrivning: "Hyra lokal",
    kontoklass: "Kostnader",
    sökord: ["lokalhyra", "hyra", "kontor", "verkstad", "lagerlokal"],
    kategori: "Kontor & fastighet",
  },
  {
    kontonummer: "5020",
    kontobeskrivning: "El, vatten, avlopp, värme",
    kontoklass: "Kostnader",
    sökord: ["el", "elräkning", "vatten", "avlopp", "uppvärmning"],
    kategori: "Kontor & fastighet",
  },
  {
    kontonummer: "5120",
    kontobeskrivning: "Larm & bevakning",
    kontoklass: "Kostnader",
    sökord: ["larm", "säkerhet", "bevakning", "väktare"],
    kategori: "Kontor & fastighet",
  },
  {
    kontonummer: "5070",
    kontobeskrivning: "Fastighetsunderhåll / reparation",
    kontoklass: "Kostnader",
    sökord: ["tak", "fönster", "fasad", "väggar", "ytterdörr"],
    kategori: "Kontor & fastighet",
  },
  {
    kontonummer: "5080",
    kontobeskrivning: "Lokalunderhåll (invändigt)",
    kontoklass: "Kostnader",
    sökord: ["armatur", "golv", "skåp", "eluttag", "måla om"],
    kategori: "Kontor & fastighet",
  },
  {
    kontonummer: "6110",
    kontobeskrivning: "Kontorsmaterial / post / trycksaker",
    kontoklass: "Kostnader",
    sökord: ["frimärken", "kuvert", "pennor", "papper", "trycksaker", "visitkort"],
    kategori: "Kontor & fastighet",
  },
  {
    kontonummer: "6071",
    kontobeskrivning: "Representation (mat, gåva, aktivitet)",
    kontoklass: "Kostnader",
    sökord: ["representation", "middag", "gåva", "evenemang", "nöje", "biljetter"],
    kategori: "Kontor & fastighet",
  },
  {
    kontonummer: "5800",
    kontobeskrivning: "Biljetter – EU",
    kontoklass: "Kostnader",
    sökord: ["tåg", "flyg", "inrikes", "biljetter", "eu"],
    kategori: "Resa & logi",
  },
  {
    kontonummer: "5801",
    kontobeskrivning: "Biljetter – utanför EU",
    kontoklass: "Kostnader",
    sökord: ["biljetter", "utrikes", "flyg", "tåg", "utland"],
    kategori: "Resa & logi",
  },
  {
    kontonummer: "5831",
    kontobeskrivning: "Kost & logi – Sverige",
    kontoklass: "Kostnader",
    sökord: ["hotell", "boende", "sverige", "logi", "12% moms"],
    kategori: "Resa & logi",
  },
  {
    kontonummer: "5832",
    kontobeskrivning: "Kost & logi – utland",
    kontoklass: "Kostnader",
    sökord: ["hotell", "övernattning", "utlandet", "resa"],
    kategori: "Resa & logi",
  },
  {
    kontonummer: "7332",
    kontobeskrivning: "Traktamente",
    kontoklass: "Kostnader",
    sökord: ["traktamente", "skattefritt", "utlägg", "resa", "dygn"],
    kategori: "Resa & logi",
  },
  {
    kontonummer: "5802",
    kontobeskrivning: "Uberavgift",
    kontoklass: "Kostnader",
    sökord: ["uber", "taxi", "resa", "transport", "app"],
    kategori: "Resa & logi",
  },
  {
    kontonummer: "7699",
    kontobeskrivning: "Friskvård",
    kontoklass: "Kostnader",
    sökord: ["gymkort", "massage", "hälsa", "friskvård", "avdragsgill"],
    kategori: "Personal",
  },
  {
    kontonummer: "7410",
    kontobeskrivning: "Pension (anställd / ägare EF)",
    kontoklass: "Personal",
    sökord: ["pension", "avsättning", "försäkring", "individuell pensionsförsäkring"],
    kategori: "Personal",
  },
  {
    kontonummer: "7571",
    kontobeskrivning: "Sjukvårdsförsäkring (60% förmån)",
    kontoklass: "Kostnader",
    sökord: ["sjukförsäkring", "vård", "privat vård", "förmån", "försäkring"],
    kategori: "Personal",
  },
  {
    kontonummer: "7610",
    kontobeskrivning: "Utbildning",
    kontoklass: "Kostnader",
    sökord: ["kurs", "fortbildning", "kompetensutveckling", "utbildning"],
    kategori: "Personal",
  },
  {
    kontonummer: "7690",
    kontobeskrivning: "Övriga personalkostnader",
    kontoklass: "Kostnader",
    sökord: ["bonus", "personal", "gåva", "tjänstebil", "kläder"],
    kategori: "Personal",
  },
  {
    kontonummer: "7210",
    kontobeskrivning: "Inhyrd personal",
    kontoklass: "Kostnader",
    sökord: ["konsult", "bemanning", "inhyrd", "extern personal"],
    kategori: "Personal",
  },
  {
    kontonummer: "5910",
    kontobeskrivning: "Reklamkostnader / mässor / trycksaker",
    kontoklass: "Kostnader",
    sökord: ["reklam", "mässa", "trycksaker", "visitkort", "annonsering", "marknadsföring"],
    kategori: "Reklam och PR",
  },
  {
    kontonummer: "5960",
    kontobeskrivning: "Reklamgåva (max 300 kr)",
    kontoklass: "Kostnader",
    sökord: ["gåva", "profilprodukt", "giveaway", "reklamgåva", "kundgåva"],
    kategori: "Reklam och PR",
  },
  {
    kontonummer: "3001",
    kontobeskrivning: "Försäljning tjänst (25% moms)",
    kontoklass: "Intäkter",
    sökord: ["tjänst", "försäljning", "intäkt", "konsult"],
    kategori: "Försäljning / Intäkter",
  },
  {
    kontonummer: "3041",
    kontobeskrivning: "Försäljning tjänst (6% moms)",
    kontoklass: "Intäkter",
    sökord: ["artist", "kultur", "konsert", "undervisning"],
    kategori: "Försäljning / Intäkter",
  },
  {
    kontonummer: "3105",
    kontobeskrivning: "Kickback (momsfri)",
    kontoklass: "Intäkter",
    sökord: ["kickback", "återbäring", "provision", "intäkt", "rabatt"],
    kategori: "Försäljning / Intäkter",
  },
  {
    kontonummer: "2018",
    kontobeskrivning: "Eget uttag / insättning",
    kontoklass: "Skulder",
    sökord: ["uttag", "insättning", "enskild firma", "egen insats", "privatkonto"],
    kategori: "Övrigt",
  },
  {
    kontonummer: "2650",
    kontobeskrivning: "Momsredovisning",
    kontoklass: "Skatt",
    sökord: ["moms", "momsredovisning", "momsrapport", "skatteverket"],
    kategori: "Övrigt",
  },
  {
    kontonummer: "2510",
    kontobeskrivning: "Preliminärskatt (enskild firma)",
    kontoklass: "Skatt",
    sökord: ["preliminärskatt", "f-skatt", "skatt", "förskottsbetalning"],
    kategori: "Övrigt",
  },
  {
    kontonummer: "2440",
    kontobeskrivning: "Leverantörsbetalningar",
    kontoklass: "Skulder",
    sökord: ["leverantör", "faktura", "betalning", "förfallodatum"],
    kategori: "Övrigt",
  },
  {
    kontonummer: "2899",
    kontobeskrivning: "Bokför kreditkortsfaktura",
    kontoklass: "Skulder",
    sökord: ["kreditkort", "faktura", "kredit", "betalning", "kortköp"],
    kategori: "Övrigt",
  },
  {
    kontonummer: "3740",
    kontobeskrivning: "Öresavrundning",
    kontoklass: "Kostnader",
    sökord: ["avrundning", "öresutjämning", "rundning", "öresavrundning"],
    kategori: "Övrigt",
  },
  {
    kontonummer: "4960",
    kontobeskrivning: "Lagerförändring",
    kontoklass: "Tillgångar",
    sökord: ["lager", "förändring", "inventering", "värdeändring"],
    kategori: "Övrigt",
  },
];
