export type Konto = {
  kontonummer: string;
  kontobeskrivning: string;
  kontoklass: string;
  sökord: string[];
  kategori: string;
};

export const accounts = [
  {
    kontonummer: "1910",
    kontobeskrivning: "Kassa",
    kontoklass: "Tillgångar",
    sökord: ["kontanter", "kassa", "pengar"],
    kategori: "Tillgångar",
  },
  {
    kontonummer: "1930",
    kontobeskrivning: "Företagskonto (bank)",
    kontoklass: "Tillgångar",
    sökord: ["bank", "konto", "företagskonto"],
    kategori: "Tillgångar",
  },
  {
    kontonummer: "1940",
    kontobeskrivning: "PlusGiro",
    kontoklass: "Tillgångar",
    sökord: ["plusgiro", "betalningar"],
    kategori: "Tillgångar",
  },
  {
    kontonummer: "1510",
    kontobeskrivning: "Kundfordringar",
    kontoklass: "Tillgångar",
    sökord: ["fordringar", "kunder", "faktura"],
    kategori: "Tillgångar",
  },
  {
    kontonummer: "1460",
    kontobeskrivning: "Varulager",
    kontoklass: "Tillgångar",
    sökord: ["lager", "varor"],
    kategori: "Tillgångar",
  },
  {
    kontonummer: "2012",
    kontobeskrivning: "Avräkning för skatter och avgifter (skattekonto)",
    kontoklass: "Tillgångar",
    sökord: ["insättning", "skattekonto", "skatteverket", "skatt", "inskott", "inbetalning"],
    kategori: "Övrigt",
  },
  {
    kontonummer: "2510",
    kontobeskrivning: "Debiterad preliminärskatt",
    kontoklass: "Skulder",
    sökord: ["preliminärskatt", "debitering", "f-skatt", "skatt att betala", "skattebesked"],
    kategori: "Övrigt",
  },
  {
    kontonummer: "4010",
    kontobeskrivning: "Inköp varor & material",
    kontoklass: "Kostnader",
    sökord: ["varor", "inköp", "material", "lager"],
    kategori: "Inköp varor & material",
    kräverSpeciellUI: true,
  },
  {
    kontonummer: "5061",
    kontobeskrivning: "Städning och renhållning",
    kontoklass: "Kostnader",
    sökord: ["städning", "kontorsstäd", "städfirma", "rengöring", "lokalvård", "renhållning"],
    kategori: "Kontor & fastighet",
  },
  {
    kontonummer: "5062",
    kontobeskrivning: "Sophämtning",
    kontoklass: "Kostnader",
    sökord: ["sopor", "sophämtning", "avfall", "renhållning", "avfallshantering", "sopavgift"],
    kategori: "Kontor & fastighet",
  },
  {
    kontonummer: "5220",
    kontobeskrivning: "Leasing/hyra av inventarier",
    kontoklass: "Kostnader",
    sökord: ["leasing", "inventarier", "dator", "kamera", "utrustning", "hyra", "verktyg"],
    kategori: "Kontor & fastighet",
  },
  {
    kontonummer: "5460",
    kontobeskrivning: "Inköp förbrukningsmaterial",
    kontoklass: "Kostnader",
    sökord: ["papper", "plastpåsar", "batterier"],
    kategori: "Inköp varor & material",
  },
  {
    kontonummer: "5410",
    kontobeskrivning: "Inköp förbrukningsinventarier",
    kontoklass: "Kostnader",
    sökord: [
      "dator",
      "telefon",
      "skrivare",
      "skanner",
      "kontorsmaskin",
      "kontorsutrustning",
      "möbler",
      "stol",
      "bord",
    ],
    kategori: "Inköp varor & material",
  },
  {
    kontonummer: "6990",
    kontobeskrivning: "Böcker & E-publikationer",
    kontoklass: "Kostnader",
    sökord: ["böcker", "e-böcker", "tidningar"],
    kategori: "Inköp varor & material",
  },
  {
    kontonummer: "6230",
    kontobeskrivning: "IT-produkter / domännamn",
    kontoklass: "Kostnader",
    sökord: ["domän", "webbhotell", "server"],
    kategori: "Inköp varor & material",
  },
  {
    kontonummer: "5615",
    kontobeskrivning: "Leasing av bil",
    kontoklass: "Kostnader",
    sökord: ["leasing", "bil", "operationell leasing", "leasingavgift"],
    kategori: "Bil och transport",
  },
  {
    kontonummer: "5612",
    kontobeskrivning: "Bilförsäkring / bilskatt",
    kontoklass: "Kostnader",
    sökord: ["försäkring", "bilskatt", "fordonsskatt"],
    kategori: "Bil och transport",
  },
  {
    kontonummer: "5610",
    kontobeskrivning: "Drivmedel – inrikes / utrikes",
    kontoklass: "Kostnader",
    sökord: ["bensin", "diesel", "etanol", "bränsle"],
    kategori: "Bil och transport",
  },
  {
    kontonummer: "5618",
    kontobeskrivning: "Parkering",
    kontoklass: "Kostnader",
    sökord: ["parkering", "avgift", "garage"],
    kategori: "Bil och transport",
  },
  {
    kontonummer: "5619",
    kontobeskrivning: "Biltvätt",
    kontoklass: "Kostnader",
    sökord: ["biltvätt", "rengöring", "tvätta bil"],
    kategori: "Bil och transport",
  },
  {
    kontonummer: "5580",
    kontobeskrivning: "Tvätt och underhåll av arbetskläder",
    kontoklass: "Kostnader",
    sökord: ["tvätt", "arbetskläder", "underhåll", "kläder", "uniform"],
    kategori: "Personal",
  },
  {
    kontonummer: "7321",
    kontobeskrivning: "Skattefria traktamenten, Sverige",
    kontoklass: "Kostnader",
    sökord: [
      "traktamente",
      "skattefritt",
      "resa",
      "inrikes",
      "dygn",
      "mat",
      "logi",
      "hotell",
      "frukost",
      "middag",
    ],
    kategori: "Resa & logi",
  },
  {
    kontonummer: "7322",
    kontobeskrivning: "Skattepliktiga traktamenten, Sverige",
    kontoklass: "Kostnader",
    sökord: [
      "traktamente",
      "skattepliktigt",
      "resa",
      "inrikes",
      "över schablon",
      "mat",
      "logi",
      "hotell",
      "frukost",
      "middag",
    ],
    kategori: "Resa & logi",
  },
  {
    kontonummer: "7323",
    kontobeskrivning: "Skattefria traktamenten, utlandet",
    kontoklass: "Kostnader",
    sökord: [
      "traktamente",
      "skattefritt",
      "resa",
      "utland",
      "dygn",
      "mat",
      "logi",
      "hotell",
      "frukost",
      "middag",
    ],
    kategori: "Resa & logi",
  },
  {
    kontonummer: "7324",
    kontobeskrivning: "Skattepliktiga traktamenten, utlandet",
    kontoklass: "Kostnader",
    sökord: [
      "traktamente",
      "skattepliktigt",
      "resa",
      "utland",
      "över schablon",
      "mat",
      "logi",
      "hotell",
      "frukost",
      "middag",
    ],
    kategori: "Resa & logi",
  },
  {
    kontonummer: "7331",
    kontobeskrivning: "Milersättning / bilersättning",
    kontoklass: "Kostnader",
    sökord: ["milersättning", "bilersättning", "körjournal", "privat bil"],
    kategori: "Bil och transport",
    kräverSpeciellUI: true,
  },
  {
    kontonummer: "7332",
    kontobeskrivning: "Skattepliktig bilersättning",
    kontoklass: "Kostnader",
    sökord: ["milersättning", "bilersättning", "körjournal", "privat bil", "över schablon"],
    kategori: "Bil och transport",
  },
  {
    kontonummer: "5616",
    kontobeskrivning: "Trängselskatt",
    kontoklass: "Kostnader",
    sökord: ["trängselskatt", "vägtull"],
    kategori: "Bil och transport",
  },
  {
    kontonummer: "5630",
    kontobeskrivning: "Transportmedelskostnader",
    kontoklass: "Kostnader",
    sökord: ["registreringsbevis", "fordonsavgifter", "trafikregister"],
    kategori: "Bil och transport",
  },
  {
    kontonummer: "5010",
    kontobeskrivning: "Hyra lokal (momsfri)",
    kontoklass: "Kostnader",
    sökord: ["hyra", "lokalhyra", "kontor", "verkstad", "lagerlokal"],
    kategori: "Kontor & fastighet",
  },
  {
    kontonummer: "5011",
    kontobeskrivning: "Hyra lokal (momspliktig)",
    kontoklass: "Kostnader",
    sökord: ["hyra", "lokalhyra", "kontor", "verkstad", "lagerlokal"],
    kategori: "Kontor & fastighet",
  },
  {
    kontonummer: "5020",
    kontobeskrivning: "El för belysning",
    kontoklass: "Kostnader",
    sökord: ["el", "belysning", "elräkning", "lampor", "elförbrukning", "ström", "elavgift"],
    kategori: "Kontor & fastighet",
  },
  {
    kontonummer: "5030",
    kontobeskrivning: "Värme",
    kontoklass: "Kostnader",
    sökord: ["värme", "uppvärmning", "element", "fjärrvärme", "uppvärmningskostnad"],
    kategori: "Kontor & fastighet",
  },
  {
    kontonummer: "5040",
    kontobeskrivning: "Vatten och avlopp",
    kontoklass: "Kostnader",
    sökord: ["vatten", "avlopp", "kran", "toalett", "avloppsavgift", "vattenförbrukning"],
    kategori: "Kontor & fastighet",
  },
  {
    kontonummer: "5120",
    kontobeskrivning: "Larm & bevakning",
    kontoklass: "Kostnader",
    sökord: ["larm", "säkerhet", "bevakning", "väktare"],
    kategori: "Kontor & fastighet",
  },
  {
    kontonummer: "5070",
    kontobeskrivning: "Fastighetsunderhåll / reparation",
    kontoklass: "Kostnader",
    sökord: ["tak", "fönster", "fasad", "väggar", "ytterdörr"],
    kategori: "Kontor & fastighet",
  },
  {
    kontonummer: "5080",
    kontobeskrivning: "Lokalunderhåll (invändigt)",
    kontoklass: "Kostnader",
    sökord: ["armatur", "golv", "skåp", "eluttag", "måla om", "målning", "renovering"],
    kategori: "Kontor & fastighet",
  },
  {
    kontonummer: "5510",
    kontobeskrivning: "Reparation och underhåll av maskiner",
    kontoklass: "Kostnader",
    sökord: [
      "reparation",
      "underhåll",
      "maskin",
      "felsökning",
      "service",
      "verkstad",
      "reservdelar",
    ],
    kategori: "Reparationer & underhåll",
  },
  {
    kontonummer: "5520",
    kontobeskrivning: "Reparation och underhåll av inventarier, verktyg och datorer",
    kontoklass: "Kostnader",
    sökord: [
      "reparation",
      "underhåll",
      "inventarier",
      "verktyg",
      "dator",
      "utrustning",
      "service",
      "felsökning",
    ],
    kategori: "Reparationer & underhåll",
  },
  {
    kontonummer: "6110",
    kontobeskrivning: "Kontorsmaterial och trycksaker",
    kontoklass: "Kostnader",
    sökord: ["kuvert", "pennor", "papper", "trycksaker", "visitkort"],
    kategori: "Kontor & fastighet",
  },
  {
    kontonummer: "6071",
    kontobeskrivning: "Representation, avdragsgill",
    kontoklass: "Kostnader",
    sökord: ["representation", "förtäring", "affärslunch", "middag", "momsavdrag", "mat", "dryck"],
    kategori: "Möten, konferens & nöjen",
  },
  {
    kontonummer: "6072",
    kontobeskrivning: "Representation, ej avdragsgill",
    kontoklass: "Kostnader",
    sökord: ["representation", "alkohol", "över 300kr", "lounge", "show", "spa"],
    kategori: "Möten, konferens & nöjen",
  },
  {
    kontonummer: "6073",
    kontobeskrivning: "Representation utomlands",
    kontoklass: "Kostnader",
    sökord: ["representation", "middag", "gåva", "evenemang", "nöje", "biljetter", "mat", "lunch"],
    kategori: "Resa & logi",
  },
  {
    kontonummer: "6991",
    kontobeskrivning: "Övriga externa kostnader, avdragsgilla",
    kontoklass: "Kostnader",
    sökord: [
      "konferens",
      "företagsevent",
      "planeringsdag",
      "möte",
      "avdragsgill",
      "konferensanläggning",
      "konferensrum",
    ],
    kategori: "Övriga externa kostnader",
  },
  {
    kontonummer: "5800",
    kontobeskrivning: "Resekostnader (gruppkonto)",
    kontoklass: "Kostnader",
    sökord: [
      "uber",
      "bolt",
      "bilpool",
      "elscooter",
      "voi",
      "lime",
      "ryde",
      "pendlarkort",
      "färja",
      "taxi",
    ],
    kategori: "Resa & logi",
  },
  {
    kontonummer: "5810",
    kontobeskrivning: "Biljetter, inrikes, 6% moms",
    kontoklass: "Kostnader",
    sökord: ["tåg", "flyg", "buss", "biljetter"],
    kategori: "Resa & logi",
  },
  {
    kontonummer: "5820",
    kontobeskrivning: "Biljetter, utrikes, momsfri",
    kontoklass: "Kostnader",
    sökord: ["biljetter", "utrikes", "flyg", "tåg", "buss"],
    kategori: "Resa & logi",
  },
  {
    kontonummer: "5831",
    kontobeskrivning: "Kost & logi – Sverige",
    kontoklass: "Kostnader",
    sökord: ["hotell", "boende", "sverige", "logi", "12% moms"],
    kategori: "Resa & logi",
    kräverSpeciellUI: true,
  },
  {
    kontonummer: "5832",
    kontobeskrivning: "Kost & logi – utland",
    kontoklass: "Kostnader",
    sökord: ["hotell", "övernattning", "utlandet", "resa"],
    kategori: "Resa & logi",
    kräverSpeciellUI: true,
  },
  {
    kontonummer: "7321",
    kontobeskrivning: "Traktamente Sverige (skattefritt)",
    kontoklass: "Kostnader",
    sökord: [
      "traktamente",
      "resa",
      "dygnsersättning",
      "skattefri",
      "inrikes",
      "tjänsteresa",
      "resetillägg",
      "kostnadsersättning",
    ],
    kategori: "Resa & logi",
    kräverSpeciellUI: true,
  },
  {
    kontonummer: "7322",
    kontobeskrivning: "Traktamente Sverige (skattepliktigt)",
    kontoklass: "Kostnader",
    sökord: [
      "traktamente",
      "skattepliktig",
      "resa",
      "resetillägg",
      "över schablon",
      "tjänsteresa",
      "ersättning",
    ],
    kategori: "Resa & logi",
    kräverSpeciellUI: true,
  },
  {
    kontonummer: "7323",
    kontobeskrivning: "Traktamente utland (skattefritt)",
    kontoklass: "Kostnader",
    sökord: [
      "utland",
      "resa",
      "traktamente",
      "skattefri",
      "normalbelopp",
      "tjänsteresa",
      "resetillägg",
      "dygn",
    ],
    kategori: "Resa & logi",
    kräverSpeciellUI: true,
  },
  {
    kontonummer: "7324",
    kontobeskrivning: "Traktamente utland (skattepliktigt)",
    kontoklass: "Kostnader",
    sökord: [
      "utland",
      "resa",
      "traktamente",
      "skattepliktig",
      "över schablon",
      "resetillägg",
      "dygnsersättning",
    ],
    kategori: "Resa & logi",
    kräverSpeciellUI: true,
  },
  {
    kontonummer: "7332",
    kontobeskrivning: "Traktamente",
    kontoklass: "Kostnader",
    sökord: ["traktamente", "skattefritt", "utlägg", "resa", "dygn"],
    kategori: "Resa & logi",
  },
  {
    kontonummer: "5802",
    kontobeskrivning: "Uberavgift",
    kontoklass: "Kostnader",
    sökord: ["uber", "taxi", "resa", "transport", "app"],
    kategori: "Resa & logi",
  },
  {
    kontonummer: "7631",
    kontobeskrivning: "Personalrepresentation, avdragsgill",
    kontoklass: "Kostnader",
    sökord: [
      "personalrepresentation",
      "intern representation",
      "personalaktivitet",
      "julbord",
      "sommarfest",
      "personalfest",
      "avdragsgill",
      "300kr",
      "middag",
      "internfest",
      "anställd",
      "intern",
      "personal",
    ],
    kategori: "Möten, konferens & nöjen",
  },
  {
    kontonummer: "7632",
    kontobeskrivning: "Personalrepresentation, ej avdragsgill",
    kontoklass: "Kostnader",
    sökord: [
      "personalrepresentation",
      "intern representation",
      "ej avdragsgill",
      "över 300kr",
      "förmån",
      "personal",
      "internfest",
      "alkohol",
      "middag",
      "evenemang",
      "gåva",
    ],
    kategori: "Möten, konferens & nöjen",
    kräverSpeciellUI: true,
  },
  {
    kontonummer: "7699",
    kontobeskrivning: "Friskvård",
    kontoklass: "Kostnader",
    sökord: ["gymkort", "massage", "hälsa", "friskvård", "avdragsgill"],
    kategori: "Personal",
  },
  {
    kontonummer: "7410",
    kontobeskrivning: "Pension (anställd / ägare EF)",
    kontoklass: "Kostnader",
    sökord: ["pension", "avsättning", "försäkring", "individuell pensionsförsäkring"],
    kategori: "Personal",
  },
  {
    kontonummer: "7571",
    kontobeskrivning: "Sjukvårdsförsäkring (60% förmån)",
    kontoklass: "Kostnader",
    sökord: ["sjukförsäkring", "vård", "privat vård", "förmån", "försäkring"],
    kategori: "Personal",
  },
  {
    kontonummer: "7610",
    kontobeskrivning: "Utbildning",
    kontoklass: "Kostnader",
    sökord: ["kurs", "fortbildning", "kompetensutveckling", "utbildning"],
    kategori: "Personal",
  },
  {
    kontonummer: "7690",
    kontobeskrivning: "Övriga personalkostnader",
    kontoklass: "Kostnader",
    sökord: [
      "bonus",
      "personal",
      "gåva",
      "julgåva",
      "jubileumsgåva",
      "minnesgåva",
      "present",
      "tjänstebil",
      "kläder",
      "medarbetare",
      "förmån",
    ],
    kategori: "Personal",
  },
  {
    kontonummer: "7210",
    kontobeskrivning: "Inhyrd personal",
    kontoklass: "Kostnader",
    sökord: [
      "inhyrd personal",
      "bemanning",
      "konsult",
      "konsultarvode",
      "extern personal",
      "frilans",
      "tjänst",
      "inhyrning",
      "resurs",
      "rekrytering",
    ],
    kategori: "Personal",
  },
  {
    kontonummer: "5910",
    kontobeskrivning: "Annonsering",
    kontoklass: "Kostnader",
    sökord: ["annonsering", "annons", "google ads", "meta ads", "ads", "kampanj"],
    kategori: "Reklam och PR",
  },
  {
    kontonummer: "5920",
    kontobeskrivning: "Utomhus- och trafikreklam",
    kontoklass: "Kostnader",
    sökord: ["utomhusreklam", "trafikreklam", "bussreklam", "billboard", "skylt", "storbild"],
    kategori: "Reklam och PR",
  },
  {
    kontonummer: "5930",
    kontobeskrivning: "Reklamtrycksaker och direktreklam",
    kontoklass: "Kostnader",
    sökord: ["trycksaker", "flyers", "broschyr", "visitkort", "reklamblad", "direktreklam"],
    kategori: "Reklam och PR",
  },
  {
    kontonummer: "5940",
    kontobeskrivning: "Utställningar och mässor",
    kontoklass: "Kostnader",
    sökord: ["mässa", "utställning", "monter", "evenemang", "expo", "event"],
    kategori: "Reklam och PR",
  },
  {
    kontonummer: "5950",
    kontobeskrivning: "Butiksreklam och återförsäljarreklam",
    kontoklass: "Kostnader",
    sökord: ["butiksreklam", "skyltning", "kampanjmaterial", "återförsäljare"],
    kategori: "Reklam och PR",
  },
  {
    kontonummer: "5960",
    kontobeskrivning: "Varuprover, reklamgåvor, presentreklam och tävlingar",
    kontoklass: "Kostnader",
    sökord: ["gåva", "giveaway", "reklamgåva", "varuprov", "tävling", "profilprodukt"],
    kategori: "Reklam och PR",
  },
  {
    kontonummer: "5970",
    kontobeskrivning: "Film-, radio-, TV- och Internetreklam",
    kontoklass: "Kostnader",
    sökord: [
      "tv-reklam",
      "radioreklam",
      "filmreklam",
      "onlineannonser",
      "internetreklam",
      "youtube",
      "spotify",
    ],
    kategori: "Reklam och PR",
  },
  {
    kontonummer: "5980",
    kontobeskrivning: "PR, institutionell reklam och sponsring",
    kontoklass: "Kostnader",
    sökord: ["pr", "sponsring", "sponsor", "institutionell reklam", "varumärkesbyggande"],
    kategori: "Reklam och PR",
  },
  {
    kontonummer: "5990",
    kontobeskrivning: "Övriga kostnader för reklam och PR",
    kontoklass: "Kostnader",
    sökord: ["övrigt", "reklam", "pr", "marknadsföring", "kampanj", "kommunikation"],
    kategori: "Reklam och PR",
  },
  {
    kontonummer: "3001",
    kontobeskrivning: "Försäljning tjänst (25% moms)",
    kontoklass: "Intäkter",
    sökord: ["tjänst", "försäljning", "intäkt", "konsult"],
    kategori: "Försäljning / Intäkter",
    kräverSpeciellUI: true,
  },
  {
    kontonummer: "3041",
    kontobeskrivning: "Försäljning tjänst (6% moms)",
    kontoklass: "Intäkter",
    sökord: ["artist", "kultur", "konsert", "undervisning"],
    kategori: "Försäljning / Intäkter",
    kräverSpeciellUI: true,
  },
  {
    kontonummer: "3105",
    kontobeskrivning: "Kickback (momsfri)",
    kontoklass: "Intäkter",
    sökord: ["kickback", "återbäring", "provision", "intäkt", "rabatt"],
    kategori: "Försäljning / Intäkter",
  },
  {
    kontonummer: "2018",
    kontobeskrivning: "Eget uttag / insättning",
    kontoklass: "Skulder",
    sökord: ["uttag", "insättning", "enskild firma", "egen insats", "privatkonto"],
    kategori: "Övrigt",
  },
  {
    kontonummer: "2650",
    kontobeskrivning: "Momsredovisning",
    kontoklass: "Skulder",
    sökord: ["moms", "momsredovisning", "momsrapport", "skatteverket"],
    kategori: "Övrigt",
  },
  {
    kontonummer: "Skatteskulder",
    kontobeskrivning: "Debiterad preliminärskatt",
    kontoklass: "Skulder",
    sökord: ["preliminärskatt", "debiterad skatt", "skattebesked", "skuld till Skatteverket"],
    kategori: "Övrigt",
  },
  {
    kontonummer: "2440",
    kontobeskrivning: "Leverantörsbetalningar",
    kontoklass: "Skulder",
    sökord: ["leverantör", "faktura", "betalning", "förfallodatum"],
    kategori: "Övrigt",
  },
  {
    kontonummer: "4960",
    kontobeskrivning: "Lagerförändring",
    kontoklass: "Kostnader",
    sökord: ["lager", "förändring", "inventering", "värdeändring"],
    kategori: "Övrigt",
  },
  {
    kontonummer: "5620",
    kontobeskrivning: "Hyrbil – inrikes",
    kontoklass: "Kostnader",
    sökord: ["hyrbil", "inrikes", "biluthyrning"],
    kategori: "Bil och transport",
  },
  {
    kontonummer: "7333",
    kontobeskrivning: "Milersättning (anställd eller extern)",
    kontoklass: "Kostnader",
    sökord: ["milersättning", "resa", "anställd", "bil"],
    kategori: "Bil och transport",
  },
  {
    kontonummer: "5617",
    kontobeskrivning: "Övriga bilkostnader",
    kontoklass: "Kostnader",
    sökord: ["bil", "kostnader", "övrigt"],
    kategori: "Bil och transport",
  },
  {
    kontonummer: "6210",
    kontobeskrivning: "Telekommunikation",
    kontoklass: "Kostnader",
    sökord: [
      "mobiltelefon",
      "telekom",
      "telefon",
      "mobil",
      "abonnemang",
      "mobilabonnemang",
      "telefoni",
    ],
    kategori: "Kontor & fastighet",
  },
  {
    kontonummer: "6230",
    kontobeskrivning: "Datakommunikation",
    kontoklass: "Kostnader",
    sökord: ["internet", "bredband", "wifi", "router", "nätverk", "datatrafik", "molntjänster"],
    kategori: "Kontor & fastighet",
  },
  {
    kontonummer: "5710",
    kontobeskrivning: "Frakter och transporter (25% moms)",
    kontoklass: "Kostnader",
    sökord: [
      "frakt",
      "post",
      "brev",
      "transport",
      "leverans",
      "logistik",
      "spedition",
      "frimärken",
    ],
    kategori: "Inköp varor & material",
  },
  {
    kontonummer: "5711",
    kontobeskrivning: "Post, frakt och transporter utan moms",
    kontoklass: "Kostnader",
    sökord: ["frakt", "post", "brev", "porto", "frimärken"],
    kategori: "Inköp varor & material",
  },
  {
    kontonummer: "5712",
    kontobeskrivning: "Frakt/post utanför EU",
    kontoklass: "Kostnader",
    sökord: ["frakt", "post", "utrikes", "tull", "utanför EU"],
    kategori: "Inköp varor & material",
  },
  {
    kontonummer: "6540",
    kontobeskrivning: "IT-tjänster",
    kontoklass: "Kostnader",
    sökord: [
      "it",
      "support",
      "datorhjälp",
      "molntjänster",
      "webbplats",
      "hemsida",
      "drift",
      "webbhotell",
      "domännamn",
      "hosting",
      "programvara",
      "nätverk",
      "it-konsult",
      "it-service",
      "google",
      "facebook",
      "meta",
      "tiktok",
      "instagram",
      "zoom",
      "amazon",
      "aws",
      "azure",
    ],
    kategori: "Inköp tjänster",
  },
  {
    kontonummer: "4530",
    kontobeskrivning: "Inköp tjänster – utanför EU (omvänd moms)",
    kontoklass: "Kostnader",
    sökord: ["utanför EU", "omvänd moms", "import tjänster", "fiktiv moms"],
    kategori: "Inköp tjänster",
    kräverSpeciellUI: true,
  },
  {
    kontonummer: "4535",
    kontobeskrivning: "Inköp tjänster – inom EU (omvänd moms)",
    kontoklass: "Kostnader",
    sökord: [
      "inom EU",
      "omvänd moms",
      "tjänster från EU",
      "import tjänst",
      "fiktiv moms",
      "eu-leverantör",
    ],
    kategori: "Inköp tjänster",
    kräverSpeciellUI: true,
  },
  {
    kontonummer: "5570",
    kontobeskrivning: "Städning av lokaler",
    kontoklass: "Kostnader",
    sökord: ["städning", "lokalstädning", "kontorsstäd", "städfirma", "renhållning", "rengöring"],
    kategori: "Inköp tjänster",
  },
  {
    kontonummer: "6550",
    kontobeskrivning: "Konsultarvoden",
    kontoklass: "Kostnader",
    sökord: [
      "konsult",
      "tjänst",
      "rådgivning",
      "konsultarvode",
      "expert",
      "frilans",
      "inhyrd konsult",
    ],
    kategori: "Inköp tjänster",
  },
  {
    kontonummer: "6530",
    kontobeskrivning: "Redovisningstjänster",
    kontoklass: "Kostnader",
    sökord: ["bokföring", "bokför.com", "redovisning", "deklaration", "bokföringsprogram"],
    kategori: "Inköp tjänster",
  },
  {
    kontonummer: "6570",
    kontobeskrivning: "Banktjänster",
    kontoklass: "Kostnader",
    sökord: ["bank", "avgift", "bankavgift", "kontoavgift"],
    kategori: "Inköp tjänster",
  },
  {
    kontonummer: "7411",
    kontobeskrivning: "Direktpension (ej avdragsgill)",
    kontoklass: "Kostnader",
    sökord: ["direktpension", "kapitalförsäkring", "pension", "ej avdragsgill"],
    kategori: "Personal",
  },
  {
    kontonummer: "7572",
    kontobeskrivning: "Försäkringar (ej avdragsgilla)",
    kontoklass: "Kostnader",
    sökord: ["försäkring", "privat", "ej avdragsgill", "sjukförsäkring", "personlig"],
    kategori: "Personal",
  },
  {
    kontonummer: "7698",
    kontobeskrivning: "Företagslägenheter / bostadsförmån",
    kontoklass: "Kostnader",
    sökord: ["lägenhet", "förmån", "bostad", "hyra", "anställd"],
    kategori: "Personal",
  },
  {
    kontonummer: "6992",
    kontobeskrivning: "Bolagsverket (avdragsgill)",
    kontoklass: "Kostnader",
    sökord: ["bolagsverket", "ändringsanmälan", "registrering", "avgift", "avdragsgill"],
    kategori: "Skatter och avgifter",
  },

  {
    kontonummer: "6993",
    kontobeskrivning: "Bolagsverket (ej avdragsgill)",
    kontoklass: "Kostnader",
    sökord: ["bolagsverket", "nyregistrering", "avgift", "ej avdragsgill", "ej avdrag"],
    kategori: "Skatter och avgifter",
  },
  {
    kontonummer: "6999",
    kontobeskrivning: "Ej avdragsgilla kostnader",
    kontoklass: "Kostnader",
    sökord: ["ej avdragsgill", "ej avdrag", "privat", "kostnad"],
    kategori: "Skatter och avgifter",
  },
  {
    kontonummer: "2012",
    kontobeskrivning: "Skattekonto (enskild firma)",
    kontoklass: "Skulder",
    sökord: [
      "insättning",
      "skattekonto",
      "skatteverket",
      "skatt",
      "inskott",
      "inbetalning",
      "konto",
    ],
    kategori: "Skatter och avgifter",
  },
  {
    kontonummer: "5410",
    kontobeskrivning: "Förbrukningsinventarier",
    kontoklass: "Kostnader",
    sökord: [
      "inventarie",
      "förbrukningsinventarie",
      "dator",
      "mobil",
      "skrivare",
      "mindre inköp",
      "under gräns",
    ],
    kategori: "Inköp varor & material",
  },
  {
    kontonummer: "1220",
    kontobeskrivning: "Inventarier och verktyg",
    kontoklass: "Tillgångar",
    sökord: [
      "anläggningstillgång",
      "inventarie",
      "verktyg",
      "investering",
      "tillgång",
      "stadigvarande bruk",
      "3 år",
      "prisbasbelopp",
    ],
    kategori: "Tillgångar",
  },
  {
    kontonummer: "2610",
    kontobeskrivning: "Utgående moms, 25 %",
    kontoklass: "Skulder",
    sökord: ["moms", "utgående", "25%", "försäljning", "momspliktig"],
    kategori: "Moms",
  },
  {
    kontonummer: "2611",
    kontobeskrivning: "Utgående moms på försäljning inom Sverige, 25 %",
    kontoklass: "Skulder",
    sökord: ["moms", "försäljning", "inom Sverige", "25%", "utgående moms"],
    kategori: "Moms",
  },
  {
    kontonummer: "2612",
    kontobeskrivning: "Utgående moms på egna uttag, 25 %",
    kontoklass: "Skulder",
    sökord: ["egna uttag", "moms", "25%", "utgående moms"],
    kategori: "Moms",
  },
  {
    kontonummer: "2613",
    kontobeskrivning: "Utgående moms för uthyrning, 25 %",
    kontoklass: "Skulder",
    sökord: ["uthyrning", "lokal", "moms", "25%", "utgående moms"],
    kategori: "Moms",
  },
  {
    kontonummer: "2614",
    kontobeskrivning: "Utgående moms, omvänd betalningsskyldighet, 25 %",
    kontoklass: "Skulder",
    sökord: ["omvänd moms", "25%", "utgående moms", "omvänd skattskyldighet"],
    kategori: "Moms",
  },
  {
    kontonummer: "2615",
    kontobeskrivning: "Utgående moms import av varor, 25 %",
    kontoklass: "Skulder",
    sökord: ["import", "moms", "tull", "25%", "utgående moms", "varor"],
    kategori: "Moms",
  },
  {
    kontonummer: "2620",
    kontobeskrivning: "Utgående moms, 12 %",
    kontoklass: "Skulder",
    sökord: ["moms", "utgående", "12%", "försäljning"],
    kategori: "Moms",
  },
  {
    kontonummer: "2621",
    kontobeskrivning: "Utgående moms på försäljning inom Sverige, 12 %",
    kontoklass: "Skulder",
    sökord: ["moms", "12%", "försäljning", "sverige", "utgående"],
    kategori: "Moms",
  },
  {
    kontonummer: "2622",
    kontobeskrivning: "Utgående moms på egna uttag, 12 %",
    kontoklass: "Skulder",
    sökord: ["moms", "egna uttag", "utgående", "12%"],
    kategori: "Moms",
  },
  {
    kontonummer: "2623",
    kontobeskrivning: "Utgående moms för uthyrning, 12 %",
    kontoklass: "Skulder",
    sökord: ["moms", "uthyrning", "utgående", "12%"],
    kategori: "Moms",
  },
  {
    kontonummer: "2624",
    kontobeskrivning: "Utgående moms, omvänd betalningsskyldighet, 12 %",
    kontoklass: "Skulder",
    sökord: ["moms", "omvänd", "betalningsskyldighet", "utgående", "12%"],
    kategori: "Moms",
  },
  {
    kontonummer: "2625",
    kontobeskrivning: "Utgående moms import av varor, 12 %",
    kontoklass: "Skulder",
    sökord: ["moms", "import", "utanför EU", "utgående", "12%"],
    kategori: "Moms",
  },
  {
    kontonummer: "2626",
    kontobeskrivning: "Utgående moms VMB 12 %",
    kontoklass: "Skulder",
    sökord: ["moms", "vmb", "vinstmarginal", "12%"],
    kategori: "Moms",
  },
  {
    kontonummer: "2628",
    kontobeskrivning: "Vilande utgående moms, 12 %",
    kontoklass: "Skulder",
    sökord: ["moms", "vilande", "utgående", "12%"],
    kategori: "Moms",
  },
  {
    kontonummer: "2630",
    kontobeskrivning: "Utgående moms, 6 %",
    kontoklass: "Skulder",
    sökord: ["moms", "utgående", "6%", "försäljning"],
    kategori: "Moms",
  },
  {
    kontonummer: "2631",
    kontobeskrivning: "Utgående moms på försäljning inom Sverige, 6 %",
    kontoklass: "Skulder",
    sökord: ["moms", "försäljning", "sverige", "6%", "utgående"],
    kategori: "Moms",
  },
  {
    kontonummer: "2632",
    kontobeskrivning: "Utgående moms på egna uttag, 6 %",
    kontoklass: "Skulder",
    sökord: ["moms", "egna uttag", "utgående", "6%"],
    kategori: "Moms",
  },
  {
    kontonummer: "2633",
    kontobeskrivning: "Utgående moms för uthyrning, 6 %",
    kontoklass: "Skulder",
    sökord: ["moms", "uthyrning", "utgående", "6%"],
    kategori: "Moms",
  },
  {
    kontonummer: "2634",
    kontobeskrivning: "Utgående moms, omvänd betalningsskyldighet, 6 %",
    kontoklass: "Skulder",
    sökord: ["moms", "omvänd", "betalningsskyldighet", "utgående", "6%"],
    kategori: "Moms",
  },
  {
    kontonummer: "2635",
    kontobeskrivning: "Utgående moms import av varor, 6 %",
    kontoklass: "Skulder",
    sökord: ["moms", "import", "utanför EU", "utgående", "6%"],
    kategori: "Moms",
  },
  {
    kontonummer: "2636",
    kontobeskrivning: "Utgående moms VMB 6 %",
    kontoklass: "Skulder",
    sökord: ["moms", "vmb", "vinstmarginal", "6%"],
    kategori: "Moms",
  },
  {
    kontonummer: "2638",
    kontobeskrivning: "Vilande utgående moms, 6 %",
    kontoklass: "Skulder",
    sökord: ["moms", "vilande", "utgående", "6%"],
    kategori: "Moms",
  },
  {
    kontonummer: "4515",
    kontobeskrivning: "Inköp av varor från annat EU-land, 25 %",
    kontoklass: "Kostnader",
    sökord: ["inköp", "eu", "varor", "25%", "omvänd moms"],
    kategori: "Inköp varor & material",
  },
  {
    kontonummer: "4516",
    kontobeskrivning: "Inköp av varor från annat EU-land, 12 %",
    kontoklass: "Kostnader",
    sökord: ["inköp", "eu", "varor", "12%", "omvänd moms"],
    kategori: "Inköp varor & material",
  },
  {
    kontonummer: "4517",
    kontobeskrivning: "Inköp av varor från annat EU-land, 6 %",
    kontoklass: "Kostnader",
    sökord: ["inköp", "eu", "varor", "6%", "omvänd moms"],
    kategori: "Inköp varor & material",
  },
  {
    kontonummer: "4518",
    kontobeskrivning: "Inköp av varor från annat EU-land, momsfri",
    kontoklass: "Kostnader",
    sökord: ["inköp", "eu", "varor", "momsfri"],
    kategori: "Inköp varor & material",
  },
  {
    kontonummer: "4530",
    kontobeskrivning: "Inköp av tjänster från ett land utanför EU",
    kontoklass: "Kostnader",
    sökord: ["tjänster", "utanför EU", "omvänd moms", "import"],
    kategori: "Inköp tjänster",
  },
  {
    kontonummer: "4531",
    kontobeskrivning: "Inköp av tjänster från ett land utanför EU, 25 % moms",
    kontoklass: "Kostnader",
    sökord: ["tjänster", "utanför EU", "25%", "omvänd moms"],
    kategori: "Inköp tjänster",
  },
  {
    kontonummer: "4532",
    kontobeskrivning: "Inköp av tjänster från ett land utanför EU, 12 % moms",
    kontoklass: "Kostnader",
    sökord: ["tjänster", "utanför EU", "12%", "omvänd moms"],
    kategori: "Inköp tjänster",
  },
  {
    kontonummer: "4533",
    kontobeskrivning: "Inköp av tjänster från ett land utanför EU, 6 % moms",
    kontoklass: "Kostnader",
    sökord: ["tjänster", "utanför EU", "6%", "omvänd moms"],
    kategori: "Inköp tjänster",
  },
  {
    kontonummer: "4535",
    kontobeskrivning: "Inköp av tjänster från annat EU-land, 25 %",
    kontoklass: "Kostnader",
    sökord: ["tjänster", "eu", "25%", "omvänd moms", "import"],
    kategori: "Inköp tjänster",
  },
  {
    kontonummer: "4536",
    kontobeskrivning: "Inköp av tjänster från annat EU-land, 12 %",
    kontoklass: "Kostnader",
    sökord: ["tjänster", "eu", "12%", "omvänd moms", "import"],
    kategori: "Inköp tjänster",
  },
  {
    kontonummer: "4537",
    kontobeskrivning: "Inköp av tjänster från annat EU-land, 6 %",
    kontoklass: "Kostnader",
    sökord: ["tjänster", "eu", "6%", "omvänd moms", "import"],
    kategori: "Inköp tjänster",
  },
  {
    kontonummer: "4538",
    kontobeskrivning: "Inköp av tjänster från annat EU-land, momsfri",
    kontoklass: "Kostnader",
    sökord: ["tjänster", "eu", "momsfri", "import"],
    kategori: "Inköp tjänster",
  },
  {
    kontonummer: "4540",
    kontobeskrivning: "Import av varor",
    kontoklass: "Kostnader",
    sökord: ["import", "varor", "utanför EU", "tull", "moms", "omvänd"],
    kategori: "Inköp varor & material",
  },
  {
    kontonummer: "4545",
    kontobeskrivning: "Import av varor, 25 % moms",
    kontoklass: "Kostnader",
    sökord: ["import", "25%", "varor", "tull", "utanför EU"],
    kategori: "Inköp varor & material",
  },
  {
    kontonummer: "4546",
    kontobeskrivning: "Import av varor, 12 % moms",
    kontoklass: "Kostnader",
    sökord: ["import", "12%", "varor", "tull", "utanför EU"],
    kategori: "Inköp varor & material",
  },
  {
    kontonummer: "4547",
    kontobeskrivning: "Import av varor, 6 % moms",
    kontoklass: "Kostnader",
    sökord: ["import", "6%", "varor", "tull", "utanför EU"],
    kategori: "Inköp varor & material",
  },
  {
    kontonummer: "2899",
    kontobeskrivning: "Bokför kreditkortsfaktura",
    kontoklass: "Skulder",
    sökord: ["kreditkort", "faktura", "betalning", "kortfaktura", "visa", "mastercard"],
    kategori: "Övrigt",
  },
  {
    kontonummer: "4960",
    kontobeskrivning: "Förändring av lager av handelsvaror (ökat värde)",
    kontoklass: "Kostnader",
    sökord: ["lager", "lagerökning", "lagerförändring", "inventering", "lagervärde", "ökning"],
    kategori: "Övrigt",
  },
  {
    kontonummer: "4960",
    kontobeskrivning: "Förändring av lager av handelsvaror (minskat värde)",
    kontoklass: "Kostnader",
    sökord: [
      "lager",
      "lagerminskning",
      "lagerförändring",
      "inventering",
      "lagervärde",
      "minskning",
    ],
    kategori: "Övrigt",
  },
  {
    kontonummer: "6500",
    kontobeskrivning: "Övriga externa tjänster (gruppkonto)",
    kontoklass: "Kostnader",
    sökord: ["extern tjänst", "utbildning", "tjänst", "föreläsning", "rådgivning", "25% moms"],
    kategori: "Inköp tjänster",
  },
  {
    kontonummer: "5200",
    kontobeskrivning: "Hyra av anläggningstillgångar",
    kontoklass: "Kostnader",
    sökord: [
      "leasing",
      "hyra",
      "maskiner",
      "teknisk anläggning",
      "hyrmaskin",
      "teknik",
      "utrustning",
    ],
    kategori: "Inköp tjänster",
  },
  {
    kontonummer: "8311",
    kontobeskrivning: "Ränteintäkter från bank",
    kontoklass: "Intäkter",
    sökord: ["ränteintäkt", "bankränta", "ränta", "sparkonto", "intäkt"],
    kategori: "Finansiella intäkter",
  },
  {
    kontonummer: "6064",
    kontobeskrivning: "Factoringavgifter",
    kontoklass: "Kostnader",
    sökord: ["factoring", "avgift", "klarna", "påminnelse", "finansiering"],
    kategori: "Övriga externa kostnader",
  },
  {
    kontonummer: "6570",
    kontobeskrivning: "Bankkostnader",
    kontoklass: "Kostnader",
    sökord: ["bank", "avgifter", "överföring", "kontohantering", "tjänst"],
    kategori: "Finansiella kostnader",
  },
  {
    kontonummer: "2350",
    kontobeskrivning: "Andra långfristiga skulder till kreditinstitut",
    kontoklass: "Skulder",
    sökord: ["lån", "kredit", "banklån", "skuld", "institut"],
    kategori: "Långfristiga skulder",
  },
  {
    kontonummer: "1931",
    kontobeskrivning: "Sparkonto",
    kontoklass: "Tillgångar",
    sökord: ["sparande", "sparkonto", "pengar", "räntekonto"],
    kategori: "Likvida medel",
  },
  {
    kontonummer: "1684",
    kontobeskrivning: "Kortfristiga fordringar hos leverantörer",
    kontoklass: "Tillgångar",
    sökord: ["fordran", "bolt", "uber", "foodora", "kvitto"],
    kategori: "Kortfristiga fordringar",
  },
  {
    kontonummer: "3011",
    kontobeskrivning: "Försäljning tjänster inom Sverige, 25 % moms",
    kontoklass: "Intäkter",
    sökord: ["försäljning", "tjänst", "sverige", "25%", "moms"],
    kategori: "Tjänsteintäkter",
  },
  {
    kontonummer: "3012",
    kontobeskrivning: "Försäljning tjänster inom Sverige, 12 % moms",
    kontoklass: "Intäkter",
    sökord: ["försäljning", "tjänst", "sverige", "12%", "moms"],
    kategori: "Tjänsteintäkter",
  },
  {
    kontonummer: "3013",
    kontobeskrivning: "Försäljning tjänster inom Sverige, 6 % moms",
    kontoklass: "Intäkter",
    sökord: ["försäljning", "tjänst", "sverige", "6%", "moms"],
    kategori: "Tjänsteintäkter",
  },
  {
    kontonummer: "3001",
    kontobeskrivning: "Försäljning varor inom Sverige, 25 % moms",
    kontoklass: "Intäkter",
    sökord: ["försäljning", "vara", "sverige", "25%", "moms"],
    kategori: "Varuförsäljning",
  },
  {
    kontonummer: "3002",
    kontobeskrivning: "Försäljning varor inom Sverige, 12 % moms",
    kontoklass: "Intäkter",
    sökord: ["försäljning", "vara", "sverige", "12%", "moms"],
    kategori: "Varuförsäljning",
  },
  {
    kontonummer: "3003",
    kontobeskrivning: "Försäljning varor inom Sverige, 6 % moms",
    kontoklass: "Intäkter",
    sökord: ["försäljning", "vara", "sverige", "6%", "moms"],
    kategori: "Varuförsäljning",
  },
  {
    kontonummer: "3004",
    kontobeskrivning: "Försäljning varor inom Sverige, momsfri",
    kontoklass: "Intäkter",
    sökord: ["försäljning", "vara", "sverige", "momsfri"],
    kategori: "Varuförsäljning",
  },
  {
    kontonummer: "3308",
    kontobeskrivning: "Försäljning tjänster till annat EU-land",
    kontoklass: "Intäkter",
    sökord: ["eu", "tjänst", "försäljning", "inom eu", "momsfri"],
    kategori: "Tjänsteintäkter",
  },
  {
    kontonummer: "3108",
    kontobeskrivning: "Försäljning varor till annat EU-land, momsfri",
    kontoklass: "Intäkter",
    sökord: ["eu", "vara", "försäljning", "export", "momsfri"],
    kategori: "Varuförsäljning",
  },
  {
    kontonummer: "3106",
    kontobeskrivning: "Försäljning varor till annat EU-land, momspliktig",
    kontoklass: "Intäkter",
    sökord: ["eu", "vara", "försäljning", "moms"],
    kategori: "Varuförsäljning",
  },
  {
    kontonummer: "1513",
    kontobeskrivning: "Kundfordringar – delad faktura",
    kontoklass: "Tillgångar",
    sökord: ["kundfordran", "faktura", "delad betalning", "fakturaandel"],
    kategori: "Kundfordringar",
  },
  {
    kontonummer: "3912",
    kontobeskrivning: "Arrendeintäkter",
    kontoklass: "Intäkter",
    sökord: ["arrende", "hyra", "intäkt", "mark", "lokal"],
    kategori: "Rörelseintäkter",
  },
  {
    kontonummer: "3980",
    kontobeskrivning: "Erhållna offentliga bidrag",
    kontoklass: "Intäkter",
    sökord: ["bidrag", "offentligt", "stöd", "bidragsintäkt"],
    kategori: "Övriga rörelseintäkter",
  },
  {
    kontonummer: "1580",
    kontobeskrivning: "Fordringar för kontokort och kuponger",
    kontoklass: "Tillgångar",
    sökord: ["kontokort", "kuponger", "fordran", "betalning", "tillgång"],
    kategori: "Kortfristiga fordringar",
  },
  {
    kontonummer: "1460",
    kontobeskrivning: "Lager av handelsvaror",
    kontoklass: "Tillgångar",
    sökord: ["lager", "varor", "lagerinventering", "handelsvaror"],
    kategori: "Varulager",
  },
  {
    kontonummer: "4960",
    kontobeskrivning: "Förändring av lager av handelsvaror",
    kontoklass: "Kostnader",
    sökord: ["lagerförändring", "lager", "värdering", "handelsvaror"],
    kategori: "Kostnad för sålda varor",
  },
];
